version: "3.9"

services:
  
  furnituresite:
    restart: always
    build: .
    ports: 
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - pgdb
    env_file:
      - .env

  pgdb:
    image: postgres:15
    container_name: pgdb
    volumes:
      - /home/user/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
