name: Docker Image and testing CI
env:
  APP_NAME: "furniture"
  DEPLOY_PACKAGE_NAME: furniture-deploy-ver-${{ github.sha }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  testing:
    runs-on: ubuntu-latest
    needs:
        [build]
    steps:
    - name: test message
      run: echo "test message"
    - name: print app name
      run: echo "application name - ${{ env.APP_NAME }}"
    - name: print package name
      run: echo "package name - ${{ env.DEPLOY_PACKAGE_NAME }}"
